version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
        - '8080:80'
    volumes:
        - ./app:/var/www/app
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
        - php
        - database
  php:
    container_name: php
    build:
        context: .
    ports:
        - '9000:9000'
    volumes:
        - ./app:/var/www/app
    depends_on:
        - database
  database:
    container_name: mysql_database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: facetec
        MYSQL_USER: symfony
        MYSQL_PASSWORD: symfony
    volumes:
        - ./mysql:/var/lib/mysql